language: csharp
solution: RestWithASPNETUdemy.sln
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
script:
  - cd "/RestWithASPNETUdemy 01 - Calculator/"
  - echo "Entered /RestWithASPNETUdemy 01 - Calculator/."
  - dotnet build
