version: '3.4'

services:
  db:
    image: mysql
    command:  >
      bash -c "mysqld --default-authentication-plugin=mysql_native_password
      && --init-file /home/RestWithASPNETUdemy/db/migrations/V1_0_1__Create_Table_Persons.sql"
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - "3306:3306"

  restwithaspnetudemy:
    image: restwithaspnetudemy-api
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      HOST: db
      DB_USER: root
      DB_PWD: user
    ports:
      - "80"
    links:
      - db
    depends_on:
      - db
