version: '3.4'

services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=user
      - MYSQL_DATABASE=rest_with_asp_net_udemy
    ports:
      - "3306:3306"

  restwithaspnetudemy:
    image: restwithaspnetudemy-api
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    links:
      - db
    depends_on:
      - db
